#39 Add dimensional options to keep
jarun/imgp pull request #40
Opened 2020-11-25 02:29 UTC by omidraha

#39 Add dimensional options to keep

2020-11-25 02:44 UTC, jarun commented
CI fails with:

    imgp:281:4: R1705: Unnecessary "elif" after "return" (no-else-return)
Please fix.

2020-11-25 14:31 UTC, jarun requested changes

2020-11-25 14:31 UTC, jarun commented on README.md
>    -k, --keep            skip (honors -c or --pr) images matching specified
Please indicate optional parameter correctly. Currently it appears the option doesn't take any parameter.

2020-11-25 14:31 UTC, jarun commented on README.md
> +                        hres or vres or --res=100 or
I can't remember what --res=100 here means. Can you please try to figure it out?

2020-11-25 14:31 UTC, jarun commented on README.md
> +                        -k hresxvres: skip hres/vres matching that are less than or equal hres and vres
skip images that are less than or equal to hres and vres

2020-11-25 14:31 UTC, jarun commented on imgp
> +
No unnecessary newlines for each if-else please. At least look at the existing code.

2020-11-25 14:31 UTC, jarun commented on imgp
> +    elif keep and (hres <= khres or vres <= kvres):
Should this be at line 274?

2020-11-25 14:31 UTC, jarun commented on imgp
> +    elif keep and (hres <= khres or vres <= kvres):
if keep and (scale == 100 or hres <= khres or vres <= kvres)

2020-11-25 14:31 UTC, jarun commented on imgp
> +        khres, kvres = getres(args.keep) if 'x' in args.keep else getres('{}x{}'.format(args.keep, args.keep))
No no value if passed for `keep` set khres = HRES and kvres = VRES.

2020-11-26 01:46 UTC, jarun requested changes

2020-11-26 01:46 UTC, jarun commented on imgp
> +    else:
No.

I meant if the call is:

    imgp -k
    // -k without any arguments

khres should be set to HRES and kvres should be set to VRES.

2020-11-26 01:46 UTC, jarun commented on imgp
> +        return 0
We should gracefully exit the program in this case. it's not our job to fix user input.

2020-11-26 01:46 UTC, jarun commented on README.md
> +  -k, --keep [res|hresxvres]
```
  -k, --keep [pixels|HxV]
                        - no args: skip (honors -c or --pr) images with hres/vres <= --res or --res <= 100
                        - pixels: skip images with H/V <= pixels
                        - HxV: skip images with hres <= H or vres <= V
                        [default: off]
```

2020-11-26 01:46 UTC, jarun commented on imgp
> +    if keep and (scale == 100 or hres <= khres or vres <= kvres):
`scale <= 100)`

2020-11-26 01:46 UTC, jarun commented on imgp
> +           help='-k: skip (honors -c or --pr) images matching specified hres or vres or --res=100, \
help should be:

```
                        - no args: skip (honors -c or --pr) images with hres/vres <= --res or --res <= 100
                        - pixels: skip images with H/V <= pixels
                        - HxV: skip images with hres <= H or vres <= V
                        [default: off]
```

2020-11-26 02:48 UTC, omidraha commented
Sorry I'm busy ;)
Please fix yourself,
Thanks.

2020-11-26 02:48 UTC, closed without merging

2020-11-26 07:37 UTC, jarun commented
No problem. The code is not up to the mark so far. Anyway, I'll take care of it.

2020-11-26 14:25 UTC, jarun commented
I don't think we need this per current handling. Explaining in the defect.